
insert into Cliente (Nombre, Direccion) values ('Winfield', '842 Melrose Parkway');
insert into Cliente (Nombre, Direccion) values ('Elena', '4 Northview Parkway');
insert into Cliente (Nombre, Direccion) values ('Kennett', '60 Oneill Trail');
insert into Cliente (Nombre, Direccion) values ('Phineas', '388 Mandrake Court');
insert into Cliente (Nombre, Direccion) values ('Gabey', '05958 Onsgard Pass');
insert into Cliente (Nombre, Direccion) values ('Joachim', '373 Graceland Road');
insert into Cliente (Nombre, Direccion) values ('Harland', '441 Debra Court');
insert into Cliente (Nombre, Direccion) values ('Sarajane', '922 Eagan Parkway');
insert into Cliente (Nombre, Direccion) values ('Dur', '6 Lakeland Alley');
insert into Cliente (Nombre, Direccion) values ('Nappy', '90304 Eliot Way');
insert into Cliente (Nombre, Direccion) values ('Darline', '4 Summer Ridge Plaza');
insert into Cliente (Nombre, Direccion) values ('Lilly', '220 Hooker Crossing');
insert into Cliente (Nombre, Direccion) values ('Prinz', '839 North Avenue');
insert into Cliente (Nombre, Direccion) values ('Jere', '1848 Elgar Street');
insert into Cliente (Nombre, Direccion) values ('Caryl', '0997 Doe Crossing Court');
insert into Cliente (Nombre, Direccion) values ('Alida', '814 Brentwood Terrace');
insert into Cliente (Nombre, Direccion) values ('Cloris', '1137 Dixon Lane');
insert into Cliente (Nombre, Direccion) values ('Massimiliano', '1962 Monument Lane');
insert into Cliente (Nombre, Direccion) values ('Marena', '56038 Leroy Junction');
insert into Cliente (Nombre, Direccion) values ('Seymour', '863 Lake View Circle');
insert into Cliente (Nombre, Direccion) values ('Siana', '02725 Lake View Way');
insert into Cliente (Nombre, Direccion) values ('Ramon', '41655 Dovetail Street');
insert into Cliente (Nombre, Direccion) values ('Claribel', '1130 Hallows Center');
insert into Cliente (Nombre, Direccion) values ('Kynthia', '374 Drewry Avenue');
insert into Cliente (Nombre, Direccion) values ('Tim', '3872 Holy Cross Point');
insert into Cliente (Nombre, Direccion) values ('Chucho', '5384 Saint Paul Street');
insert into Cliente (Nombre, Direccion) values ('Toby', '13234 Brickson Park Crossing');
insert into Cliente (Nombre, Direccion) values ('Danette', '91050 Norway Maple Park');
insert into Cliente (Nombre, Direccion) values ('Alvera', '6 Westport Way');
insert into Cliente (Nombre, Direccion) values ('Thorvald', '81408 Orin Alley');
insert into Cliente (Nombre, Direccion) values ('June', '09 Hovde Trail');
insert into Cliente (Nombre, Direccion) values ('Derby', '96 Northport Street');
insert into Cliente (Nombre, Direccion) values ('Sascha', '04 Sullivan Center');
insert into Cliente (Nombre, Direccion) values ('Ernst', '308 Acker Plaza');
insert into Cliente (Nombre, Direccion) values ('Kincaid', '94 Anniversary Center');
insert into Cliente (Nombre, Direccion) values ('Laura', '433 Ridgeway Park');
insert into Cliente (Nombre, Direccion) values ('Norina', '7 Maywood Street');
insert into Cliente (Nombre, Direccion) values ('Jedediah', '93016 Dennis Place');
insert into Cliente (Nombre, Direccion) values ('Gene', '2 Parkside Circle');
insert into Cliente (Nombre, Direccion) values ('Hana', '07643 Carey Alley');
insert into Cliente (Nombre, Direccion) values ('Isiahi', '8 Duke Center');
insert into Cliente (Nombre, Direccion) values ('Raychel', '1083 Oak Court');
insert into Cliente (Nombre, Direccion) values ('Valentina', '58283 Washington Way');
insert into Cliente (Nombre, Direccion) values ('Orion', '0 Mayer Lane');
insert into Cliente (Nombre, Direccion) values ('Jessalyn', '3869 Petterle Circle');
insert into Cliente (Nombre, Direccion) values ('Fidole', '25505 Corry Terrace');
insert into Cliente (Nombre, Direccion) values ('Harris', '0 Maple Wood Drive');
insert into Cliente (Nombre, Direccion) values ('Ramona', '7 Grayhawk Road');
insert into Cliente (Nombre, Direccion) values ('Kylynn', '48903 Portage Junction');
insert into Cliente (Nombre, Direccion) values ('Leo', '42467 Clarendon Circle');
insert into Cliente (Nombre, Direccion) values ('Lucais', '5781 Grayhawk Park');
insert into Cliente (Nombre, Direccion) values ('Roobbie', '35260 Prentice Pass');
insert into Cliente (Nombre, Direccion) values ('Alidia', '42 Fairfield Point');
insert into Cliente (Nombre, Direccion) values ('Will', '4 Hoffman Lane');
insert into Cliente (Nombre, Direccion) values ('Brandais', '22 Browning Plaza');
insert into Cliente (Nombre, Direccion) values ('Griswold', '31684 Iowa Point');
insert into Cliente (Nombre, Direccion) values ('Ximenez', '6 Michigan Junction');
insert into Cliente (Nombre, Direccion) values ('Kinnie', '4204 West Pass');
insert into Cliente (Nombre, Direccion) values ('Hermy', '07 Sutherland Avenue');
insert into Cliente (Nombre, Direccion) values ('Anet', '3104 Sunbrook Center');
insert into Cliente (Nombre, Direccion) values ('Boothe', '0135 Clemons Crossing');
insert into Cliente (Nombre, Direccion) values ('Trudie', '81 Starling Drive');
insert into Cliente (Nombre, Direccion) values ('Norene', '94367 Corry Place');
insert into Cliente (Nombre, Direccion) values ('Peadar', '3763 Granby Drive');
insert into Cliente (Nombre, Direccion) values ('Kennedy', '5761 Manley Parkway');
insert into Cliente (Nombre, Direccion) values ('Michel', '4128 Daystar Parkway');
insert into Cliente (Nombre, Direccion) values ('Rhea', '453 Crescent Oaks Street');
insert into Cliente (Nombre, Direccion) values ('Rebeka', '295 Lakeland Center');
insert into Cliente (Nombre, Direccion) values ('Jere', '75 Beilfuss Hill');
insert into Cliente (Nombre, Direccion) values ('Renard', '2 Moulton Point');
insert into Cliente (Nombre, Direccion) values ('Ruthie', '09 Dexter Point');
insert into Cliente (Nombre, Direccion) values ('Ninetta', '1824 Crowley Center');
insert into Cliente (Nombre, Direccion) values ('Cal', '41 Maple Avenue');
insert into Cliente (Nombre, Direccion) values ('Kimberlyn', '43237 Eastwood Court');
insert into Cliente (Nombre, Direccion) values ('Vidovik', '3613 Golden Leaf Parkway');
insert into Cliente (Nombre, Direccion) values ('Scotti', '60942 Superior Center');
insert into Cliente (Nombre, Direccion) values ('Emylee', '074 Magdeline Trail');
insert into Cliente (Nombre, Direccion) values ('Morley', '0 Summerview Junction');
insert into Cliente (Nombre, Direccion) values ('Fonzie', '74294 Artisan Drive');
insert into Cliente (Nombre, Direccion) values ('Cortie', '553 Mifflin Trail');
insert into Cliente (Nombre, Direccion) values ('Aubrey', '9 John Wall Pass');
insert into Cliente (Nombre, Direccion) values ('Kenyon', '6108 Superior Drive');
insert into Cliente (Nombre, Direccion) values ('Rebbecca', '083 Comanche Park');
insert into Cliente (Nombre, Direccion) values ('Seka', '8 Cascade Alley');
insert into Cliente (Nombre, Direccion) values ('Hoyt', '8 Laurel Lane');
insert into Cliente (Nombre, Direccion) values ('Lorri', '32309 Burning Wood Way');
insert into Cliente (Nombre, Direccion) values ('Jarret', '52965 Sycamore Circle');
insert into Cliente (Nombre, Direccion) values ('Jerome', '474 Northview Court');
insert into Cliente (Nombre, Direccion) values ('Ave', '85634 Hauk Place');
insert into Cliente (Nombre, Direccion) values ('Cinda', '2 Longview Lane');
insert into Cliente (Nombre, Direccion) values ('Saba', '41353 Menomonie Way');
insert into Cliente (Nombre, Direccion) values ('Reiko', '155 Clarendon Avenue');
insert into Cliente (Nombre, Direccion) values ('Anthe', '4 Elgar Center');
insert into Cliente (Nombre, Direccion) values ('Sada', '511 Manitowish Hill');
insert into Cliente (Nombre, Direccion) values ('Babb', '89353 Bunker Hill Court');
insert into Cliente (Nombre, Direccion) values ('Prudi', '605 Gale Center');
insert into Cliente (Nombre, Direccion) values ('Kerwin', '705 Russell Crossing');
insert into Cliente (Nombre, Direccion) values ('Petey', '36522 Schlimgen Alley');
insert into Cliente (Nombre, Direccion) values ('Ned', '527 Katie Plaza');
insert into Cliente (Nombre, Direccion) values ('Jessie', '19819 South Drive');
insert into Cliente (Nombre, Direccion) values ('Merrielle', '3239 Anzinger Street');

INSERT INTO Empleado (Nombre, Turno) VALUES ('Moise Lequeux', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Ryan Kays', 'Mañana');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Gibb Berndt', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Kimbell Minget', 'Noche');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Gordy Hanbury', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Theodosia Cuthill', 'Mañana');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Sancho Bushnell', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Sully Jenkin', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Hymie Searight', 'Mañana');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Claudian Ramsdale', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Krisha Meddows', 'Mañana');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Aurlie Esselin', 'Noche');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Rita Dayne', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Calypso Kearney', 'Tarde');
INSERT INTO Empleado (Nombre, Turno) VALUES ('Jeanie Murrthum', 'Tarde');
 -- Se hicieron 15 pues el sistema no ocupa más empleados para atender a los clientes

 insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Letter, The', 'Drama', 'Rachelle Burnapp', 2006, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('But I''m a Cheerleader', 'Comedy', 'Benyamin Aimson', 2004, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('China O''Brien', 'Action', 'Catarina Bengtsson', 1985, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Christine Jorgensen Story, The', 'Drama', 'Dalenna Janz', 2000, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Broken Hearts Club, The', 'Drama', 'Rube Congram', 1999, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Such Is Life', 'Drama', 'Craggie Oels', 2006, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Escape from Dartmoor', 'Crime', 'Rodolph Manvell', 2004, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Ballad of Narayama, The (Narayama bushiko)', 'Drama', 'Katie Bulger', 2010, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Milky Way, The (Voie lactée, La)', 'Comedy', 'Rowan Wheway', 1999, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Casino Royale', 'Action', 'Lyn Alywen', 1986, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Marshal of Finland, The (Suomen Marsalkka)', 'Drama', 'Sheryl Cater', 2012, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Offspring ', 'Horror', 'Torrence Deery', 2011, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Housebound', 'Comedy', 'Pascale Hamel', 1992, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Gleaming the Cube', 'Antiguo', 'Efrem Dade', 1944, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('The Pokrovsky Gates', 'Comedy', 'Odelinda Prestland', 2010, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Non-Stop', 'Action', 'Michelle Bristow', 1998, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Sixteen Candles', 'Comedy', 'Frances Mapledorum', 2002, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Bad Taste', 'Comedy', 'Bentlee Langlais', 2007, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Regarding Henry', 'Drama', 'Kort Abreheart', 1990, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Wrong Turn 2: Dead End', 'Action', 'Alden Moreinu', 1999, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Debtocracy', 'Documentary', 'Burt Geratt', 1996, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Dancing at the Blue Iguana', 'Drama', 'Rosy Haddick', 2010, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Simple Plan, A', 'Crime', 'Iago Leadbetter', 1991, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Nightmare City', 'Action', 'Glynn Pyke', 2009, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Flamingo Kid, The', 'Comedy', 'Sophie Cornejo', 1987, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('The Legend of Bloody Jack', 'Horror', 'Tailor Shernock', 2009, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Nazarin', 'Drama', 'Valentin Boyet', 1992, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Nanny Diaries, The', 'Comedy', 'Conny Fulk', 1990, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Invisible Invaders', 'Horror', 'Kizzee Malthouse', 2008, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Aces and Eights', 'Western', 'Papageno Boutwell', 1990, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('I Love Trouble', 'Action', 'Toiboid Matuszak', 2004, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Saimaa Gesture, The', 'Documentary', 'Merwin Megany', 1993, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Wayward Bus, The', 'Drama', 'Alyosha Carrodus', 1992, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Nun, The', 'Drama', 'Roana Cullinan', 2005, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Dark Shadows', 'Comedy', 'Carri Cockman', 1995, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Glengarry Glen Ross', 'Drama', 'Hedy Fearick', 2003, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('When Evening Falls on Bucharest or Metabolism', '(no genres listed)', 'Glynda Filasov', 2003, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Getaway, The', 'Action', 'Silvia Blay', 1961, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Mulberry Street', 'Action', 'Hillard Zylbermann', 1985, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Volga - Volga', 'Comedy', 'Antoni Drayson', 2006, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('How Stella Got Her Groove Back', 'Drama', 'Jaymee Cornner', 2002, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Rise of the Guardians', 'Adventure', 'Herta Gadney', 1995, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Sophie''s Choice', 'Drama', 'Diego Gaukroger', 2009, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('By the Bluest of Seas (U samogo sinego morya)', 'Drama', 'Margareta Maiklem', 2005, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Where the Boys Are', 'Comedy', 'Hildy MacKeig', 2003, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Butterfly', 'Drama', 'Miller Culp', 1987, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Allegheny Uprising', 'Action', 'Ilsa Manktelow', 2008, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Little Engine That Could, The', 'Animation', 'Rabbi Falconer', 2003, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Saint Ange (House of Voices)', 'Antiguo', 'Lombard Van der Velden', 1934, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Going Clear: Scientology and the Prison of Belief', 'Documentary', 'Serge Korting', 1999, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Death Note', 'Adventure', 'Hy Gyver', 2009, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Nausicaä of the Valley of the Wind (Kaze no tani no Naushika)', 'Adventure', 'Blanche Hubble', 1983, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Last Days of Disco, The', 'Comedy', 'Kele Sampey', 2002, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Flywheel', 'Drama', 'Barnard Wroath', 2010, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Report on the Party and the Guests, A (O slavnosti a hostech)', 'Drama', 'Calley Jeanenet', 2007, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Captain America', 'Action', 'Dara Beresford', 2012, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Cruel Gun Story (Kenjû zankoku monogatari)', 'Action', 'Cirilo Nisot', 2003, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Command Decision', 'Drama', 'Cristy Escott', 2011, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Bad Girls (Biches, Les)', 'Drama', 'Annie Ghelardoni', 1988, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Close-Up (Nema-ye Nazdik)', 'Drama', 'Leann Coie', 2010, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('In a World...', 'Comedy', 'Ruperta Kryska', 2008, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Disappeared, The', 'Horror', 'Susann Joul', 2012, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Living with Michael Jackson', 'Documentary', 'Sofia Morot', 1992, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Stationmaster Is on Fire - The Movie, That Is!, The (Stinsen brinner... filmen alltså)', 'Comedy', 'Jena Marsham', 2002, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Young and Prodigious T.S. Spivet, The (L''extravagant voyage du jeune et prodigieux T.S. Spivet)', 'Adventure', 'Beaufort Roddick', 2009, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Sidewalls (Medianeras)', 'Drama', 'Maximilian Bicksteth', 1994, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Moon Man', 'Animation', 'Warren McCay', 1995, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Wild Geese II', 'Action', 'Dreddy Kruse', 1996, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Shadrach', 'Drama', 'Garrek Delgaty', 2011, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Young Törless, The (Junge Törless, Der)', 'Drama', 'Alvy Pescod', 2006, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Mandela: Long Walk to Freedom', 'Drama', 'Clementius Juleff', 2009, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Moon', 'Drama', 'Lester Behn', 1991, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Command Decision', 'Drama', 'Adam Baxendale', 2001, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Recollections of the Yellow House (Recordações da Casa Amarela)', 'Comedy', 'Salvatore Rymour', 1995, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Day Lincoln Was Shot, The', 'Drama', 'Orrin Rushby', 1986, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Northanger Abbey', 'Drama', 'Schuyler Marzelle', 1993, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Severance', 'Comedy', 'Della Ronci', 1995, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Lipstick', 'Drama', 'Guenna Oldfield-Cherry', 2004, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Brazil: In the Shadow of the Stadiums', 'Documentary', 'Torrin Meads', 1998, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Piranha', 'Horror', 'Carie Pont', 2001, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Female Vampire (Les avaleuses) (Erotic Kill)', 'Horror', 'Emalee Ebrall', 2002, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Evil - In the Time of Heroes (To kako - Stin epohi ton iroon)', 'Adventure', 'Herta Birtley', 2010, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('For the Love of Movies', 'Documentary', 'Ardyth aManger', 2005, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Almost Famous', 'Drama', 'Kenn Najara', 2009, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Jack the Bear', 'Comedy', 'Vinnie O''Hagirtie', 1996, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('My Way Home (Így jöttem) ', 'Drama', 'Wyatan Dreng', 2013, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Bangkok Dangerous', 'Action', 'Bern Wiersma', 1993, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Wild Guitar', 'Drama', 'Junie Phette', 2007, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Stolen Seas', 'Adventure', 'Hernando Ellesworth', 1965, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Fidanzati, I (Fiances, The)', 'Drama', 'Georgine Motherwell', 2002, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Wild Orchid', 'Drama', 'Hercule Sinnocke', 1987, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Pulling John', 'Documentary', 'Lesli Blindt', 2003, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Private Lessons (Élève libre)', 'Drama', 'Maurene Ayris', 2006, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Just Ask My Children', 'Drama', 'Jonell Wilcot', 1993, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('Lightning Jack', 'Comedy', 'Brinn Heymes', 2009, 'VHS');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('I Married A Strange Person!', 'Animation', 'Goober Colam', 1995, 'DVD');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('The Gentleman from Epsom', 'Comedy', 'Sapphira Avrahamian', 2002, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('The Girls', 'Comedy', 'Willyt Washington', 2009, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('La La Land', 'Musical', 'Damian Chazelle ', 2016, 'BlueRay');
insert into Articulo (Titulo, Genero, Director, Año, Plataforma) values ('The Amazing Spider-Man 2', 'Action', 'Marc Webb', 2012, 'BlueRay');

INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-08-20', '2022-08-31', 148.02, 55, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-09-26', '2022-09-27', 100.6, 58, 7);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-02-12', '2021-02-19', 115.09, 41, 11);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-11-07', '2022-11-10', 115.32, 77, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-12-29', '2022-01-11', 111.59, 75, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-09-13', '2022-09-25', 173.25, 75, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-15', '2022-05-20', 170.05, 95, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-08-07', '2023-08-14', 86.47, 89, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-03-26', '2022-04-08', 164.25, 87, 6);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-10-12', '2022-10-24', 58.79, 98, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-03-19', '2022-03-20', 153.91, 9, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-10-15', '2021-10-27', 95.03, 15, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-10-21', '2023-10-26', 198.58, 33, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-08-22', '2021-09-01', 111.5, 64, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-02-02', '2023-02-10', 107.95, 57, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-07-31', '2022-08-11', 131.54, 71, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-08-03', '2021-08-17', 138.03, 31, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-10-18', '2023-10-28', 149.16, 33, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-06-11', '2023-06-20', 142.41, 51, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-07-21', '2021-07-22', 56.97, 32, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-04-01', '2022-04-02', 164.31, 17, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-31', '2022-06-13', 64.42, 10, 6);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-04-13', '2022-04-15', 114.72, 66, 7);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-07-05', '2021-07-06', 158.72, 12, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-10-22', '2022-11-01', 108.68, 71, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-08-02', '2021-08-04', 192.59, 67, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-06-30', '2022-07-12', 119.76, 28, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-11-01', '2022-11-07', 163.17, 87, 13);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-06-24', '2022-07-02', 110.91, 74, 13);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-08-24', '2023-09-05', 102.34, 98, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-11-30', '2021-12-12', 58.9, 53, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-12-05', '2021-12-11', 122.31, 89, 6);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-09-30', '2021-10-09', 115.37, 55, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-06-21', '2022-07-03', 136.42, 70, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-07-19', '2021-07-23', 175.15, 56, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-09-16', '2023-09-20', 84.17, 37, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-10-21', '2022-11-02', 102.92, 36, 11);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-05-06', '2023-05-17', 66.57, 44, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-09-17', '2023-09-25', 91.75, 48, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-04-05', '2022-04-06', 105.95, 82, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-02', '2022-05-10', 131.25, 20, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-09-13', '2021-09-21', 172.9, 25, 5);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-01-19', '2022-01-31', 70.32, 7, 5);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-07-19', '2021-08-01', 135.95, 66, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-09-02', '2021-09-07', 141.53, 40, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-07-16', '2022-07-23', 81.47, 17, 11);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-07-27', '2021-08-09', 95.43, 28, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-08-27', '2023-09-09', 198.25, 53, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-09-06', '2021-09-12', 100.56, 35, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-03-20', '2022-03-26', 140.3, 12, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-08-12', '2023-08-19', 137.7, 63, 11);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-08-05', '2023-08-19', 66.39, 52, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-07-13', '2023-07-14', 93.61, 57, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-04-28', '2022-04-29', 124.88, 24, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-06-26', '2022-06-28', 104.3, 8, 9);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-02-25', '2021-03-07', 180.78, 47, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-11-07', '2023-11-09', 50.84, 88, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-09-03', '2021-09-15', 143.3, 22, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-04-29', '2022-05-04', 54.68, 49, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-11-04', '2022-11-06', 199.12, 54, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-15', '2022-05-29', 130.84, 61, 13);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-01-26', '2023-01-28', 73.0, 74, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-07-01', '2021-07-10', 64.92, 14, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-06-30', '2021-07-01', 157.54, 83, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-10-17', '2023-10-18', 180.43, 94, 11);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-08-31', '2022-09-08', 183.84, 34, 11);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-10-23', '2023-10-28', 103.23, 35, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-01-09', '2022-01-17', 95.01, 6, 9);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-10-17', '2022-10-27', 59.97, 95, 6);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-02-02', '2023-02-09', 99.47, 65, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-01-05', '2021-01-12', 152.13, 50, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-03-25', '2022-03-30', 126.82, 41, 9);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-01-23', '2021-01-26', 131.12, 76, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-05-30', '2023-06-12', 65.31, 40, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-24', '2022-05-29', 72.07, 12, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-02-23', '2021-03-03', 51.01, 19, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-01-25', '2022-02-03', 125.21, 48, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-10-19', '2021-10-31', 54.87, 77, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-01-28', '2022-02-10', 87.41, 59, 13);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2020-12-16', '2020-12-17', 137.08, 66, 4);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-11-29', '2021-12-04', 92.85, 44, 12);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-01-28', '2021-02-08', 128.15, 11, 9);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-03-11', '2021-03-17', 89.0, 34, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-04-20', '2022-05-03', 108.12, 15, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-12-25', '2023-01-07', 101.93, 3, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-12-13', '2022-12-15', 166.19, 47, 13);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-09-13', '2023-09-17', 80.73, 66, 1);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-11-11', '2022-11-22', 78.91, 12, 7);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-01-20', '2023-01-27', 65.73, 97, 14);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-10-07', '2022-10-12', 81.79, 99, 5);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-01-25', '2021-02-03', 155.91, 94, 10);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-07-09', '2023-07-20', 107.85, 51, 9);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2021-08-11', '2021-08-23', 105.6, 76, 5);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-08', '2022-05-17', 105.11, 74, 3);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-05-27', '2022-06-08', 137.63, 91, 15);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-03-31', '2022-04-10', 133.37, 94, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-09-13', '2022-09-23', 199.65, 71, 2);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-05-29', '2023-05-30', 71.92, 58, 5);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2022-11-07', '2022-11-19', 112.11, 47, 8);
INSERT INTO Ticket (FechaAlquiler, FechaDevolucion, Total, IDcliente, IDempleado) VALUES ('2023-11-17', '2023-11-27', 99.72, 37, 14);

INSERT INTO Incluye (IDticket, IDarticulo) VALUES (57, 89);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (57, 26);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (100, 87);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (17, 72);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (44, 78);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (77, 65);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (74, 9);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (51, 61);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (50, 22);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (75, 96);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (78, 38);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (56, 58);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (51, 78);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (54, 41);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (99, 78);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (60, 17);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (22, 19);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (59, 50);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (1, 19);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (48, 16);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (3, 87);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (26, 77);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (99, 97);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (85, 79);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (37, 16);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (92, 42);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (3, 90);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (47, 33);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (7, 19);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (67, 44);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (73, 90);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (63, 35);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (100, 11);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (73, 19);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (82, 32);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (41, 35);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (74, 97);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (33, 96);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (45, 45);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (58, 65);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (38, 48);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (14, 1);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (10, 33);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (72, 8);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (31, 55);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (65, 8);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (97, 26);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (85, 16);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (19, 94);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (59, 41);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (81, 15);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (83, 71);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (21, 5);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (36, 18);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (34, 55);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (15, 90);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (44, 100);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (26, 58);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (10, 21);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (53, 92);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (25, 98);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (81, 62);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (30, 1);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (62, 15);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (37, 5);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (68, 43);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (32, 72);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (25, 47);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (37, 56);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (41, 18);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (84, 10);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (44, 31);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (69, 99);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (76, 86);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (32, 75);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (29, 20);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (96, 15);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (70, 23);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (29, 8);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (73, 13);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (61, 2);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (82, 61);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (97, 99);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (74, 29);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (5, 60);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (32, 29);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (19, 78);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (9, 67);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (73, 55);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (48, 63);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (47, 84);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (71, 4);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (96, 35);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (84, 60);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (11, 8);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (80, 39);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (47, 16);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (5, 96);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (48, 67);
INSERT INTO Incluye (IDticket, IDarticulo) VALUES (2, 56);