-- ADMINISTRADORES

INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (1, 'Brent Box', 'bbox0@free.fr', 'uP1}Fq/w', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (2, 'Maureene Carslake', 'mcarslake1@bbc.co.uk', 'jX4&chmo5`7', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (3, 'Krystalle Doel', 'kdoel2@wikispaces.com', 'gM6"{b2r', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (4, 'Elonore Franck', 'efranck3@cornell.edu', 'bI0~.=pK?P.2K', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (5, 'Cassi Tennock', 'ctennock4@youtu.be', 'dV6(Lf"x', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (6, 'Edythe Boddymead', 'eboddymead5@shutterfly.com', 'qV5\hJq<UhTPK', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (7, 'Lucia Littlechild', 'llittlechild6@businesswire.com', 'gX2?(Q?&#`Xx', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (8, 'Pet Speedin', 'pspeedin7@mozilla.com', 'kR5~9Q`A', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (9, 'Brunhilde Pollett', 'bpollett8@accuweather.com', 'pF2~R|h(', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (10, 'Matt Reeveley', 'mreeveley9@mediafire.com', 'jD6''nj0\YKgk', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (11, 'Opaline Bewshaw', 'obewshawa@google.cn', 'jF3,ZWHa\v', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (12, 'Jordain Bellon', 'jbellonb@sitemeter.com', 'rQ8@BI0X!mOol!3', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (13, 'Dun Sansom', 'dsansomc@xinhuanet.com', 'kB7"7"iY', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (14, 'Lindsay Rowler', 'lrowlerd@statcounter.com', 'jS7<p(4Z5U', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (15, 'Roland Broomhead', 'rbroomheade@gov.uk', 'wS1\k7E5', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (16, 'Kasey Gildroy', 'kgildroyf@purevolume.com', 'jG8`|~y7lEC', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (17, 'Perry Ternouth', 'pternouthg@flickr.com', 'vJ5)?(NJ\3@Xr|<F', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (18, 'Munroe Blaksley', 'mblaksleyh@slate.com', 'pY2@Q_Nf0AW', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (19, 'Sergei Biggerdike', 'sbiggerdikei@twitpic.com', 'tB5~48ee', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (20, 'Danila Dominec', 'ddominecj@ning.com', 'vO4/,)qUi3', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (21, 'Marianna Ebbin', 'mebbink@usnews.com', 'vY3,e+{JY/q!sMD', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (22, 'Ilysa Pierson', 'ipiersonl@fda.gov', 'aD8`QR+,L(W4jX', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (23, 'Hester Kenner', 'hkennerm@shop-pro.jp', 'rF8\I#JA#!', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (24, 'Selia Lightoller', 'slightollern@techcrunch.com', 'gJ9_"An#B\u#?', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (25, 'Filia Wenban', 'fwenbano@aboutads.info', 'xN7+i`9(|Vz%|j0', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (26, 'Andrus Scrooby', 'ascroobyp@cisco.com', 'oE1\9Aa''*mh?+7+@', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (27, 'Vic Clapson', 'vclapsonq@ocn.ne.jp', 'yY2*x8Co\@kVD', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (28, 'Luther Benez', 'lbenezr@gravatar.com', 'xJ4$Q`N2d', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (29, 'Edita Gready', 'egreadys@virginia.edu', 'eP7#`Zg+sTPut~', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (30, 'Violante Kemster', 'vkemstert@prweb.com', 'rQ3*DTv~Xs3', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (31, 'Candice Pitson', 'cpitsonu@shutterfly.com', 'tQ5_v$A>Th\g,', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (32, 'Steward Wilflinger', 'swilflingerv@mlb.com', 'dW2\f6"v8', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (33, 'Miquela Poltun', 'mpoltunw@geocities.com', 'yE7*{QSgK4D3_W7L', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (34, 'Raddy Buckbee', 'rbuckbeex@princeton.edu', 'bG0!r&VDUlfqdprc', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (35, 'La verne Folkard', 'lverney@parallels.com', 'yT8=x2>eJ%<jVN', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (36, 'Rosaline Dahlen', 'rdahlenz@zdnet.com', 'fE4$~LpbyW1R.yxn', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (37, 'Minerva Imms', 'mimms10@pagesperso-orange.fr', 'dW9~z/|5wL"+HANh', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (38, 'Delbert Hein', 'dhein11@upenn.edu', 'kJ1%/nWgVRN`?<M', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (39, 'Welsh Faires', 'wfaires12@usatoday.com', 'mO1@UhRi&a#', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (40, 'Suzanna Atwood', 'satwood13@delicious.com', 'sK3_+UYz?EHLb"ZL', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (41, 'Nikolos Westrey', 'nwestrey14@hao123.com', 'tW9(YAj&', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (42, 'Robb Duffell', 'rduffell15@mac.com', 'cE7?AcT''xJU<', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (43, 'Nertie Kearford', 'nkearford16@jiathis.com', 'uD2@F+/l0)%9)yv,', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (44, 'Niall Breslane', 'nbreslane17@ow.ly', 'rL5>z1Mwq+Bd,}', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (45, 'Christian Frays', 'cfrays18@forbes.com', 'mF4.bTj8Xvz', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (46, 'Alika Mold', 'amold19@hud.gov', 'hH7@%94+4', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (47, 'Kenyon Still', 'kstill1a@unesco.org', 'eC1)As(tD1', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (48, 'Sapphira Gandy', 'sgandy1b@prnewswire.com', 'cB3@\cuu', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (49, 'Malanie Unwins', 'munwins1c@multiply.com', 'gN2<$B&?ve', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (50, 'Glen Notti', 'gnotti1d@tiny.cc', 'yG3{G2c06Yg', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (51, 'Maye Benmore', 'mbenmore1e@thetimes.co.uk', 'jH7''G_>`A4', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (52, 'Delphinia Hastilow', 'dhastilow1f@jalbum.net', 'jP8*x>9j<', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (53, 'Ax Dobrowolski', 'adobrowolski1g@geocities.jp', 'sJ9?r8cMFQ"x+', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (54, 'Aggy Van der Krui', 'avan1h@state.tx.us', 'cW8=kg_32+9', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (55, 'Melamie Hamnet', 'mhamnet1i@ow.ly', 'nI5(_4*8Ov|z|', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (56, 'Bartolomeo Longthorne', 'blongthorne1j@mozilla.com', 'lB8}DP/t"/R', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (57, 'Patrice Megroff', 'pmegroff1k@qq.com', 'kT2#{dp&xq!YV>d~', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (58, 'Dannie Cradduck', 'dcradduck1l@gnu.org', 'gW5~gPumV7_', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (59, 'Talbot Arnley', 'tarnley1m@admin.ch', 'sT8>cgPK&/UWGNZ', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (60, 'Nicolle Stanett', 'nstanett1n@techcrunch.com', 'mK2~U1kp', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (61, 'Bourke Fishenden', 'bfishenden1o@mac.com', 'dM3/gqDk`2<5Tm', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (62, 'Ysabel Filby', 'yfilby1p@cnet.com', 'tQ2}HHN._FgP', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (63, 'Gareth Domingues', 'gdomingues1q@army.mil', 'eC8=Ohf#5_', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (64, 'Brynne Richardeau', 'brichardeau1r@theatlantic.com', 'bR3{he8ukGC', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (65, 'Arnuad Haville', 'ahaville1s@wordpress.org', 'nF8`H0.+yS', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (66, 'Lexis Skiggs', 'lskiggs1t@shareasale.com', 'fR9>c%w}G<+B', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (67, 'Randie Willock', 'rwillock1u@addthis.com', 'kN4"h=D!{4hJxp', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (68, 'Alessandra Siss', 'asiss1v@flickr.com', 'oP2@wq7(UC5>N$|L', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (69, 'Lotte Rossander', 'lrossander1w@histats.com', 'jM8~tuOmT1#', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (70, 'Mort Sainter', 'msainter1x@ocn.ne.jp', 'sT7|~BC5S=WLJT', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (71, 'Sidoney Shortin', 'sshortin1y@surveymonkey.com', 'iD7*vV3VmZ', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (72, 'Cull Beldham', 'cbeldham1z@geocities.jp', 'iL9_<Ti}', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (73, 'Merralee De Caroli', 'mde20@goo.gl', 'yH8!bj3sY#xL8w{', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (74, 'Keelby MacFayden', 'kmacfayden21@xinhuanet.com', 'wL7#lXa},X/KL/VE', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (75, 'Had Carmont', 'hcarmont22@go.com', 'rJ5!6Hch7}76K0`', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (76, 'Genvieve Trye', 'gtrye23@comcast.net', 'yP1\+_o/', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (77, 'Trixy Talboy', 'ttalboy24@rambler.ru', 'jR5`{SQze?', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (78, 'Adrienne Rameaux', 'arameaux25@constantcontact.com', 'hA6|"n&>_b%&', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (79, 'Wright Bramwich', 'wbramwich26@dell.com', 'aS5&NpWuNF`ifPl', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (80, 'Matt Dronsfield', 'mdronsfield27@wp.com', 'yJ9''h(V6@72FGkc', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (81, 'Julio Clausner', 'jclausner28@whitehouse.gov', 'oG1*%WbN~W5y', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (82, 'Lindie Titterington', 'ltitterington29@tripadvisor.com', 'pY7$?#>?)gk{"', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (83, 'Rosella Widocks', 'rwidocks2a@bloglines.com', 'dX8#*MH$bCXe&9B', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (84, 'Hale Beams', 'hbeams2b@furl.net', 'yT8{rka(vYwV', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (85, 'Leland Benkin', 'lbenkin2c@macromedia.com', 'rS8\<Md`l*bsr_', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (86, 'Madalena Ockland', 'mockland2d@seesaa.net', 'mY8#AF=/''!J|y8', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (87, 'Norine Rymell', 'nrymell2e@discovery.com', 'pS9+RAZ8x6', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (88, 'Erik Kreuzer', 'ekreuzer2f@nbcnews.com', 'wK6$uo).@U', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (89, 'Meredeth D''Costa', 'mdcosta2g@delicious.com', 'xZ0?+pZ<O%/6gWc', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (90, 'Sergeant Koop', 'skoop2h@hibu.com', 'aF6_,BlRKQzE', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (91, 'Heida Greasley', 'hgreasley2i@google.it', 'dG9._KE\n.x(yHJ{', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (92, 'Andie Iacovone', 'aiacovone2j@artisteer.com', 'vB9+UQ''}ci', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (93, 'Tricia Ivel', 'tivel2k@jalbum.net', 'lG2~B1V_', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (94, 'Glyn Benezet', 'gbenezet2l@surveymonkey.com', 'hC7$!7w"%1(JlTcV', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (95, 'Kessiah Vooght', 'kvooght2m@typepad.com', 'gT2)@fp%?', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (96, 'Mavra Kaubisch', 'mkaubisch2n@sakura.ne.jp', 'zD5.DOrPFNL''4', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (97, 'Alvan Possa', 'apossa2o@printfriendly.com', 'rX9"qT,Y)h', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (98, 'Grover Leall', 'gleall2p@chicagotribune.com', 'dN3''sdC6', 2);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (99, 'Konstantine Dealey', 'kdealey2q@uol.com.br', 'bI6\BAO<LHi+c', 1);
INSERT INTO ADMINISTRADOR (ID_Admin, Nombre, Correo, Contrasena, Tipo_Admin) VALUES (100, 'Porter Riddington', 'priddington2r@t.co', 'lM2<&B1uATO', 1);

-- JUGADORES

INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (1, 'Reece Swin', 'rswin0@infoseek.co.jp', 'mV7$HwDt68>', 63);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (2, 'Culver MacKintosh', 'cmackintosh1@youtube.com', 'xI3"iTp@M4eQHWG\', 100);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (3, 'Chelsea Ruegg', 'cruegg2@shop-pro.jp', 'dR7+LG)g', 53);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (4, 'Olive Daleman', 'odaleman3@51.la', 'fF3''KhR"F0c>R7Ce', 64);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (5, 'Jenelle Kibbye', 'jkibbye4@liveinternet.ru', 'sT6_aYA>j*6c', 2);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (6, 'Manfred Catton', 'mcatton5@forbes.com', 'tO9"tWTS*nL0''', 57);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (7, 'Marylinda Bohlje', 'mbohlje6@wix.com', 'mY9`''bx\L252W', 34);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (8, 'Morton Porcas', 'mporcas7@sfgate.com', 'kK4=hRDF,(v', 56);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (9, 'Sayre Bradock', 'sbradock8@unicef.org', 'aI2.xUtS', 39);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (10, 'Cleon Boswell', 'cboswell9@w3.org', 'kT4?6Kfb_', 52);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (11, 'Austin Jakoubec', 'ajakoubeca@tiny.cc', 'wR3''+xL>*u', 12);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (12, 'Jacquie Wharlton', 'jwharltonb@edublogs.org', 'vQ6}@Y7jZT.L?df', 89);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (13, 'Waite MacTague', 'wmactaguec@nbcnews.com', 'qZ4=6c{II4Y0', 26);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (14, 'Hartwell Dablin', 'hdablind@symantec.com', 'qC0*%hz!=(''y', 50);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (15, 'Tedd O''Hone', 'tohonee@istockphoto.com', 'nA5$}MO/,', 12);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (16, 'Rooney Vorley', 'rvorleyf@nymag.com', 'eI1`9Z)qhZz0mY7', 55);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (17, 'Justino Bohlje', 'jbohljeg@miitbeian.gov.cn', 'bP8$WLXHj', 29);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (18, 'Mickey Mereweather', 'mmereweatherh@cloudflare.com', 'nF2_i*T>7~v}', 99);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (19, 'Norry Melbury', 'nmelburyi@ezinearticles.com', 'kH5(<hXz6C|`~C5*', 84);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (20, 'Almeria Christoforou', 'achristoforouj@smh.com.au', 'uJ4"''+!0#O%b+H', 74);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (21, 'Haley Peach', 'hpeachk@myspace.com', 'sE3|J9\D95DN', 76);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (22, 'Tabb Hardington', 'thardingtonl@nature.com', 'lJ9~uDlf', 27);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (23, 'Nikolos Lake', 'nlakem@intel.com', 'hP9/)T7"z', 100);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (24, 'Ulrikaumeko Chaloner', 'uchalonern@123-reg.co.uk', 'gZ4}BSvR>/>5_JI', 5);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (25, 'Jayme Barthelmes', 'jbarthelmeso@hugedomains.com', 'mJ3%v''UctbIl', 17);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (26, 'Agustin Sygroves', 'asygrovesp@eepurl.com', 'jJ5,<&(}|2<Yn', 13);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (27, 'Creight Stadden', 'cstaddenq@army.mil', 'zV3''2brnC', 48);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (28, 'Merilee Llewellen', 'mllewellenr@bloomberg.com', 'xE0~rdqC|wh{Z', 45);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (29, 'Falito Bewlie', 'fbewlies@cnbc.com', 'qV4?}gK}?AiFU!{', 78);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (30, 'Cobby Grishagin', 'cgrishagint@cnn.com', 'rH8#30''P{oq)W5', 53);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (31, 'Sherwin Medeway', 'smedewayu@imageshack.us', 'xC3\w?''&YNd{', 91);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (32, 'Hilda Pilbury', 'hpilburyv@apple.com', 'uN4!3p*S}r#y~9V', 1);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (33, 'Malchy Kivlehan', 'mkivlehanw@pbs.org', 'tS8`Fkt(gAH9i', 83);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (34, 'Gardiner Aberkirdo', 'gaberkirdox@gov.uk', 'uR2&bHEmnWK', 48);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (35, 'Jilleen Rudledge', 'jrudledgey@fc2.com', 'hF8,!6Y$Ko', 14);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (36, 'Salomo MacBrearty', 'smacbreartyz@usda.gov', 'jH4%fR1A5rCd(', 81);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (37, 'Dagny Pindar', 'dpindar10@bbc.co.uk', 'lG4+j@8o1<87g.', 80);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (38, 'Franny Teck', 'fteck11@skype.com', 'nS3>@F|Im*9w9', 84);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (39, 'Goldia MacAree', 'gmacaree12@businesswire.com', 'zT1+&AhgXyON', 54);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (40, 'Easter Ellcock', 'eellcock13@mlb.com', 'kC4*8x&WM/e', 92);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (41, 'Tuesday Falconar', 'tfalconar14@miitbeian.gov.cn', 'tM9>kEQ!D+JV', 51);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (42, 'Vivian Santer', 'vsanter15@webmd.com', 'kZ7{%Kgq2m>', 22);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (43, 'Lanita Thurber', 'lthurber16@shinystat.com', 'pW8,Yd(MO#_Xq', 89);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (44, 'Carmen Burg', 'cburg17@deliciousdays.com', 'mC1$4l5d0K{*', 78);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (45, 'Bruis Martinson', 'bmartinson18@cafepress.com', 'gA1~6}Q*%piGx', 66);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (46, 'Luisa Muckeen', 'lmuckeen19@bloglines.com', 'iM4{DjW4+gGh', 65);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (47, 'Alwin Dei', 'adei1a@opensource.org', 'yY0<<3)q}{9$', 45);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (48, 'Cinderella Chrichton', 'cchrichton1b@ibm.com', 'bF6*\)P>pRE', 93);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (49, 'Franklyn Aykroyd', 'faykroyd1c@howstuffworks.com', 'hX8*+MuO%FM%OD', 41);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (50, 'Laverne Marco', 'lmarco1d@wp.com', 'xP8(h@sguWr', 43);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (51, 'Griffy Skudder', 'gskudder1e@ed.gov', 'hU5_mYcRSqL''3G+', 8);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (52, 'Raynard Jelly', 'rjelly1f@etsy.com', 'tG7''KY''LcqtyN2<H', 76);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (53, 'Tadio Patmore', 'tpatmore1g@people.com.cn', 'gM5@=Ux}BhaQ2$#', 24);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (54, 'Sibylle Mansour', 'smansour1h@cisco.com', 'zR1_A%4+0x{)mS', 97);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (55, 'Tamarah Bullers', 'tbullers1i@sciencedirect.com', 'cM2}(hu(~Gr|<', 35);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (56, 'Gardiner Heitz', 'gheitz1j@reverbnation.com', 'yD2@|fS!KS<cl{*!', 53);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (57, 'Elisa Larvor', 'elarvor1k@sogou.com', 'cN2`V#_SUpK!32"', 77);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (58, 'Avery Sopp', 'asopp1l@networkadvertising.org', 'pE2}QTIjE_W"({\', 68);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (59, 'Roderigo Purkess', 'rpurkess1m@sun.com', 'kC9.03u}ogsdF2s', 48);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (60, 'Mitzi Dearnaly', 'mdearnaly1n@dell.com', 'pB2%g0VWz2}7c', 57);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (61, 'Minna Brandle', 'mbrandle1o@mapy.cz', 'tS9,F''f@v6~S&', 98);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (62, 'Fairleigh Garms', 'fgarms1p@netvibes.com', 'qN4>2Ja*', 22);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (63, 'Eimile Crisford', 'ecrisford1q@nbcnews.com', 'bP6`gFCPjog/|?E', 20);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (64, 'Dan Heaselgrave', 'dheaselgrave1r@webs.com', 'cO1*z?}5', 66);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (65, 'Salvador Kilmartin', 'skilmartin1s@lycos.com', 'nA6>Mhm|', 19);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (66, 'Renato Ingle', 'ringle1t@admin.ch', 'bP3/jZk!', 98);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (67, 'Armin Broomfield', 'abroomfield1u@cnbc.com', 'xT1@vv\82&"X<', 17);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (68, 'Willa Broadfield', 'wbroadfield1v@telegraph.co.uk', 'eY5`X,py"G,)8~}', 66);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (69, 'Yolanthe Joynson', 'yjoynson1w@desdev.cn', 'fP6}AL\b86', 22);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (70, 'Arie Blunn', 'ablunn1x@imdb.com', 'oW5$N)uby>d1MKH', 46);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (71, 'Catina Vanshin', 'cvanshin1y@jugem.jp', 'fO0?Z|}U|(IfTrq', 33);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (72, 'Joshuah Lebel', 'jlebel1z@wikipedia.org', 'cU2*EQIQ''}SMnK5', 47);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (73, 'Sylvan Ferrotti', 'sferrotti20@google.de', 'tP6?%dfq.<rr', 30);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (74, 'Gayle Cadogan', 'gcadogan21@dyndns.org', 'kC8}<,<GO9FxTQ#f', 3);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (75, 'Emmit Infantino', 'einfantino22@homestead.com', 'lV7(Ig%Q!VQ', 26);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (76, 'Brigham Klimt', 'bklimt23@virginia.edu', 'gP6''$dY*?#(x', 94);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (77, 'Elissa McGarahan', 'emcgarahan24@nydailynews.com', 'hC2|<RHaceDHgW', 43);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (78, 'Jerrylee Ginner', 'jginner25@globo.com', 'fR8(fPaXw.cvs2', 65);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (79, 'Arnold Teeney', 'ateeney26@blogtalkradio.com', 'bU1$?m8.dW}il', 43);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (80, 'Carma Burr', 'cburr27@edublogs.org', 'dE6?%PK*nZTr''K', 58);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (81, 'Dasya O''Shavlan', 'doshavlan28@linkedin.com', 'oU4}X{Q~`H%', 5);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (82, 'Guthry Tansill', 'gtansill29@w3.org', 'hN4+pDe=BZLh8v', 50);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (83, 'Waly Woodlands', 'wwoodlands2a@jigsy.com', 'mZ3_BOO,9#~', 62);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (84, 'Wynnie Greenside', 'wgreenside2b@dailymotion.com', 'qR6}ZEf,STJvc', 69);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (85, 'Claude Whiting', 'cwhiting2c@nytimes.com', 'aY6*ql6P', 13);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (86, 'Sloane Weldrick', 'sweldrick2d@skyrock.com', 'aY1@nL"NG$', 13);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (87, 'Levi Harbage', 'lharbage2e@google.com.hk', 'pG2>xi?7nsA}', 19);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (88, 'Danyette Forestall', 'dforestall2f@mozilla.org', 'fZ1$E$s''<ix', 79);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (89, 'Luca Wressell', 'lwressell2g@tmall.com', 'iV7+8fnA', 54);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (90, 'Cecil Godby', 'cgodby2h@google.co.uk', 'oA1$oVOD5', 64);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (91, 'Adeline Elintune', 'aelintune2i@census.gov', 'jM6>1?TCjV(e', 48);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (92, 'Harri Maciaszek', 'hmaciaszek2j@360.cn', 'iH3?9sV4t~V"4', 35);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (93, 'Ferrell Tabert', 'ftabert2k@rakuten.co.jp', 'sP6+z1pB3S"y<A', 73);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (94, 'Sioux Mc Harg', 'smc2l@i2i.jp', 'eH1?)}vf8', 33);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (95, 'Jarvis Lerwell', 'jlerwell2m@howstuffworks.com', 'pX7%1,`|8xM', 31);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (96, 'Kalina Milazzo', 'kmilazzo2n@patch.com', 'lY6{_{{Pi&QHg.)\', 13);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (97, 'Breena Bootes', 'bbootes2o@ucsd.edu', 'lS2\U7n45d{kX\}{', 2);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (98, 'Gualterio Minghella', 'gminghella2p@w3.org', 'tO1#&$x7I_', 100);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (99, 'Winfred Dukesbury', 'wdukesbury2q@bbc.co.uk', 'cK2>UxLo31N1"ju', 64);
INSERT INTO JUGADOR (Id_Jugador, Nombre, Correo, Contrasena, Nivel) VALUES (100, 'Barbi Twizell', 'btwizell2r@smh.com.au', 'nI7|UaTY9#Wk_$u', 78);


-- TORNEOS  

INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (1, 55, 'First Nudie Musical, The', 'Comedy|Musical', 'seize extensible portals', 37, 'Finalizado', '2023-12-18 10:47:27', '2024-04-01 22:47:09');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (2, 47, 'Love Walked In', 'Drama|Thriller', 'transition best-of-breed markets', 43, 'Finalizado', '2023-12-05 14:39:48', '2024-01-09 17:18:59');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (3, 52, 'Italianamerican', 'Documentary', 'brand enterprise ROI', 36, 'Finalizado', '2023-12-10 05:28:47', '2024-03-23 11:28:01');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (4, 90, 'Rent-a-Cat', 'Comedy|Drama', 'deploy back-end e-commerce', 30, 'Disponible', '2023-12-12 01:19:45', '2024-03-20 17:09:35');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (5, 77, 'Hangmen Also Die', 'Drama|War', 'implement sexy solutions', 12, 'En curso', '2023-12-07 16:35:26', '2024-03-04 05:56:31');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (6, 76, 'Divo, Il', 'Drama', 'embrace intuitive bandwidth', 32, 'Disponible', '2023-12-12 19:26:06', '2024-02-24 05:54:37');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (7, 48, 'Young Unknowns, The', 'Drama', 'syndicate back-end web services', 28, 'Finalizado', '2023-12-22 15:52:51', '2024-01-08 14:12:14');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (8, 29, 'Blood Shack', 'Horror', 'seize e-business platforms', 36, 'En curso', '2023-12-29 09:18:58', '2024-01-31 20:31:01');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (9, 82, 'Squeeze', 'Drama', 'exploit sexy e-services', 13, 'En curso', '2023-12-13 22:54:31', '2024-03-10 11:36:59');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (10, 24, 'Medea', 'Drama', 'drive proactive e-markets', 45, 'Finalizado', '2023-12-22 02:36:42', '2024-02-01 00:18:40');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (11, 54, 'Cornered', 'Film-Noir|Thriller', 'reinvent revolutionary experiences', 16, 'Finalizado', '2023-12-06 00:36:41', '2024-04-17 14:39:27');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (12, 43, 'Touch of Zen, A (Xia nu)', 'Action|Adventure', 'utilize innovative niches', 39, 'En curso', '2023-12-17 08:35:59', '2024-03-03 07:24:25');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (13, 89, 'Bolt', 'Action|Adventure|Animation|Children|Comedy', 'innovate holistic mindshare', 43, 'Disponible', '2023-12-14 20:13:00', '2024-03-26 16:10:38');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (14, 38, 'This Happy Breed', 'Comedy|Drama', 'iterate 24/7 schemas', 14, 'En curso', '2023-12-21 01:41:13', '2024-02-13 01:07:55');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (15, 16, 'League of Ordinary Gentlemen, A', 'Documentary', 'disintermediate bricks-and-clicks action-items', 20, 'En curso', '2023-12-02 13:04:16', '2024-02-27 02:46:13');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (16, 12, 'The Story of Robin Hood and His Merrie Men', 'Action|Adventure|Children', 'incubate cutting-edge infrastructures', 22, 'En curso', '2023-12-16 12:12:56', '2024-01-19 16:19:07');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (17, 49, 'Better Tomorrow III: Love and Death in Saigon, A', 'Action|Thriller|War', 'grow virtual methodologies', 45, 'En curso', '2023-12-09 20:26:51', '2024-01-25 03:07:31');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (18, 37, 'Lilies', 'Drama|Fantasy|Romance', 'monetize out-of-the-box supply-chains', 15, 'Disponible', '2023-12-05 13:27:43', '2024-04-29 02:18:44');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (19, 22, 'Dark Tower, The', 'Drama|Thriller', 'expedite granular markets', 33, 'Finalizado', '2023-12-07 22:04:26', '2024-02-21 15:57:35');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (20, 75, 'Ape, The', 'Horror|Sci-Fi', 'incentivize cross-platform users', 36, 'Disponible', '2023-12-21 02:33:47', '2024-03-20 06:21:08');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (21, 41, 'Dance with Me', 'Drama|Romance', 'syndicate B2C e-markets', 24, 'Disponible', '2023-12-13 01:16:08', '2024-02-24 09:08:36');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (22, 4, 'Dog of Flanders, A', 'Drama', 'strategize value-added methodologies', 36, 'En curso', '2023-12-15 11:46:15', '2024-03-25 05:46:58');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (23, 53, 'Dead Space: Aftermath', 'Animation|Horror|Sci-Fi', 'enhance transparent content', 37, 'En curso', '2023-12-15 15:15:06', '2024-01-20 01:42:18');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (24, 92, 'Les Feux Arctiques (Arktiset tulet)', 'Documentary|Drama', 'repurpose strategic synergies', 47, 'Disponible', '2023-12-28 19:46:56', '2024-04-26 02:56:18');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (25, 82, 'Antz', 'Adventure|Animation|Children|Comedy|Fantasy', 'exploit revolutionary systems', 25, 'Finalizado', '2023-12-13 20:55:41', '2024-01-22 03:32:05');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (26, 60, 'Tinker, Tailor, Soldier, Spy', 'Drama|Thriller', 'seize visionary supply-chains', 40, 'Disponible', '2023-12-08 12:30:33', '2024-02-24 17:29:35');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (27, 44, 'Many Rivers to Cross', 'Comedy|Romance|Western', 'mesh strategic e-tailers', 40, 'Finalizado', '2023-12-19 13:24:41', '2024-03-13 19:44:41');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (28, 7, 'Tremors', 'Comedy|Horror|Sci-Fi', 'exploit holistic deliverables', 20, 'Finalizado', '2023-12-28 15:14:23', '2024-01-15 08:47:33');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (29, 44, 'Closet, The (Placard, Le)', 'Comedy', 'expedite customized mindshare', 17, 'Disponible', '2023-12-05 06:58:20', '2024-03-07 06:37:18');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (30, 34, 'Aileen: Life and Death of a Serial Killer', 'Documentary', 'seize front-end initiatives', 35, 'En curso', '2023-12-06 16:25:47', '2024-03-30 04:26:48');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (31, 2, 'Evelyn Prentice', 'Drama|Mystery|Romance', 'engage B2B technologies', 27, 'Finalizado', '2023-12-29 18:54:30', '2024-03-10 14:13:59');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (32, 84, 'Fright to the Finish', '(no genres listed)', 'architect 24/365 ROI', 11, 'Finalizado', '2023-12-20 09:35:53', '2024-04-02 01:28:19');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (33, 100, 'Wizard of Baghdad, The', 'Comedy|Fantasy|Musical', 'iterate mission-critical relationships', 18, 'Finalizado', '2023-12-02 11:07:53', '2024-01-17 06:17:53');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (34, 61, 'Half Moon (a.k.a. Niwemang)', 'Drama|War', 'aggregate dynamic e-tailers', 38, 'Finalizado', '2023-12-21 05:15:50', '2024-02-23 09:48:57');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (35, 12, 'Hudson Hawk', 'Action|Adventure|Comedy', 'enhance best-of-breed relationships', 43, 'Disponible', '2023-12-10 16:13:57', '2024-01-13 00:22:05');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (36, 70, 'For Queen and Country', 'Drama', 'synergize web-enabled technologies', 35, 'Disponible', '2023-12-14 11:53:23', '2024-04-01 09:22:37');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (37, 26, 'Number 23, The', 'Drama|Mystery|Thriller', 'grow front-end supply-chains', 15, 'Disponible', '2023-12-08 07:11:52', '2024-04-21 12:54:31');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (38, 92, 'It Started with Eve', 'Comedy|Musical|Romance', 'utilize granular web-readiness', 32, 'En curso', '2023-12-05 14:02:36', '2024-01-16 15:35:22');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (39, 54, 'Enemy of the State', 'Action|Thriller', 'deliver next-generation experiences', 37, 'Finalizado', '2023-12-15 17:14:45', '2024-03-24 06:18:44');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (40, 37, 'The Water Diviner', 'Action|Drama|War', 'grow cross-media mindshare', 29, 'En curso', '2023-12-05 15:49:47', '2024-03-26 12:15:19');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (41, 54, 'Nina Takes a Lover', 'Comedy|Romance', 'scale compelling networks', 30, 'Disponible', '2023-12-18 19:35:41', '2024-02-24 11:33:45');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (42, 68, 'Godson, The', 'Comedy|Crime', 'leverage dot-com supply-chains', 39, 'Finalizado', '2023-12-06 23:45:59', '2024-01-18 10:13:43');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (43, 38, 'Gung Ho', 'Comedy|Drama', 'target web-enabled e-commerce', 20, 'Disponible', '2023-12-11 03:58:03', '2024-04-08 00:46:06');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (44, 72, 'Pyaar Ka Punchnama', 'Comedy|Drama|Romance', 'implement ubiquitous infomediaries', 42, 'En curso', '2023-12-20 12:31:17', '2024-03-23 09:07:39');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (45, 21, 'Winnie the Pooh and a Day for Eeyore', 'Animation|Children', 'reintermediate 24/365 infrastructures', 35, 'Disponible', '2023-12-07 11:52:20', '2024-02-26 07:28:13');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (46, 10, 'On the Road to Emmaus (Emmauksen tiellä)', 'Comedy|Drama|Musical', 'transition 24/7 convergence', 28, 'Disponible', '2023-12-16 05:01:06', '2024-04-22 09:38:28');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (47, 68, 'Secret Policeman''s Other Ball, The', 'Comedy|Documentary|Musical', 'productize clicks-and-mortar ROI', 48, 'Disponible', '2023-12-01 17:36:04', '2024-03-07 07:29:28');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (48, 46, 'Barber of Siberia, The (Sibirskij tsiryulnik)', 'Drama|Romance', 'mesh scalable initiatives', 39, 'En curso', '2023-12-11 15:29:22', '2024-02-26 11:18:47');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (49, 3, 'Ronin', 'Action|Crime|Thriller', 'incubate strategic content', 36, 'Disponible', '2023-12-27 18:14:14', '2024-04-14 04:24:16');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (50, 61, 'Fail-Safe', 'Drama|Thriller|War', 'aggregate plug-and-play e-business', 50, 'En curso', '2023-12-11 01:41:10', '2024-01-24 12:53:02');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (51, 55, 'Who Killed Bambi? (Qui a tué Bambi?)', 'Drama|Thriller', 'empower out-of-the-box partnerships', 11, 'Disponible', '2023-12-15 06:45:38', '2024-02-12 04:22:06');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (52, 33, 'Daisy Miller', 'Drama', 'recontextualize back-end infomediaries', 32, 'Disponible', '2023-12-19 04:00:15', '2024-04-19 01:26:58');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (53, 93, 'Hellraiser: Inferno', 'Horror', 'harness back-end portals', 41, 'En curso', '2023-12-13 07:23:42', '2024-01-03 18:45:28');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (54, 93, 'Bo Burnham: Words, Words, Words', 'Comedy', 'innovate end-to-end networks', 11, 'Finalizado', '2023-12-14 04:33:58', '2024-01-16 12:23:38');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (55, 81, 'Off and Running ', 'Documentary', 'productize sexy portals', 41, 'Finalizado', '2023-12-13 03:04:17', '2024-03-22 05:46:45');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (56, 32, 'Spasmo', 'Mystery|Thriller', 'productize mission-critical infomediaries', 31, 'Finalizado', '2023-12-15 14:16:35', '2024-04-19 14:41:30');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (57, 86, 'In the Realms of the Unreal', 'Animation|Documentary', 'engineer next-generation e-services', 42, 'Disponible', '2023-12-03 07:13:52', '2024-01-02 06:29:04');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (58, 74, 'Wizard, The', 'Adventure|Children|Comedy|Drama', 'whiteboard rich e-tailers', 15, 'Finalizado', '2023-12-28 09:30:37', '2024-02-20 18:31:43');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (59, 73, 'Defiant Ones, The', 'Adventure|Crime|Drama|Thriller', 'mesh visionary networks', 48, 'Finalizado', '2023-12-28 10:44:09', '2024-01-12 08:11:50');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (60, 28, 'Big Top Pee-Wee', 'Adventure|Children|Comedy', 'deploy bleeding-edge relationships', 38, 'Finalizado', '2023-12-23 23:29:19', '2024-03-26 03:56:52');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (61, 2, 'Shark in Venice', 'Action|Horror|Thriller', 'reinvent best-of-breed architectures', 33, 'Finalizado', '2023-12-30 01:46:40', '2024-03-28 11:50:35');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (62, 31, 'Pitkä kuuma kesä', 'Comedy|Drama', 'grow efficient e-services', 49, 'Finalizado', '2023-12-16 09:36:36', '2024-04-07 02:35:08');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (63, 13, 'Tomorrow Night', 'Comedy|Drama', 'incentivize clicks-and-mortar solutions', 26, 'En curso', '2023-12-24 18:56:13', '2024-03-24 11:33:39');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (64, 32, 'Mystery Science Theater 3000: The Movie', 'Comedy|Sci-Fi', 'scale magnetic synergies', 48, 'Disponible', '2023-12-06 13:09:28', '2024-02-09 05:49:53');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (65, 56, 'Interrogation, The (Kuulustelu)', 'Drama', 'synergize impactful supply-chains', 34, 'Disponible', '2023-12-20 16:43:52', '2024-03-09 20:36:26');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (66, 44, '30 Days of Night: Dark Days', 'Horror|Thriller', 'revolutionize seamless paradigms', 39, 'Disponible', '2023-12-17 15:47:23', '2024-03-08 20:46:41');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (67, 78, 'Blown Away', 'Action|Thriller', 'grow mission-critical platforms', 41, 'Disponible', '2023-12-16 12:34:21', '2024-03-31 13:04:04');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (68, 97, 'Cloudburst', 'Adventure|Comedy|Drama', 'synthesize web-enabled platforms', 44, 'Finalizado', '2023-12-22 09:17:44', '2024-03-27 05:49:48');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (69, 67, 'Ginger and Fred (Ginger e Fred)', 'Comedy|Drama', 'whiteboard distributed functionalities', 36, 'En curso', '2023-12-13 17:01:39', '2024-01-26 09:35:34');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (70, 12, 'Miss Bala', 'Action|Adventure|Drama|Thriller', 'brand user-centric convergence', 47, 'Finalizado', '2023-12-28 23:21:31', '2024-03-23 21:11:20');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (71, 54, 'Sugar & Spice', 'Comedy', 'transform mission-critical supply-chains', 11, 'Finalizado', '2023-12-13 16:52:57', '2024-02-21 04:39:18');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (72, 42, 'Land of the Pharaohs', 'Drama', 'cultivate sticky architectures', 44, 'En curso', '2023-12-29 18:58:31', '2024-02-22 10:19:14');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (73, 24, 'Holes', 'Adventure|Children|Comedy|Mystery', 'extend best-of-breed web-readiness', 30, 'En curso', '2023-12-29 07:44:14', '2024-04-25 23:08:25');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (74, 9, 'Place at the Table, A', 'Documentary', 'innovate strategic eyeballs', 15, 'Finalizado', '2023-12-02 22:31:30', '2024-02-20 20:04:22');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (75, 72, 'Great Muppet Caper, The', 'Children|Comedy', 'drive distributed vortals', 39, 'Finalizado', '2023-12-04 02:24:39', '2024-04-24 06:06:50');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (76, 15, 'Hitchcock', 'Drama', 'streamline proactive applications', 36, 'Disponible', '2023-12-12 09:55:18', '2024-02-07 22:16:23');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (77, 91, 'Gulliver''s Travels', 'Adventure|Animation|Children', 'mesh user-centric networks', 16, 'En curso', '2023-12-25 23:13:25', '2024-03-31 23:13:42');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (78, 57, 'Underground: The Julian Assange Story', 'Drama', 'e-enable customized applications', 45, 'En curso', '2023-12-20 07:33:36', '2024-04-24 06:54:12');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (79, 51, 'Woman in the Meadow (Nainen kedolla)', 'Drama|Romance|Thriller', 'engineer viral metrics', 21, 'Finalizado', '2023-12-15 11:13:48', '2024-01-07 22:29:23');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (80, 10, 'Ice Age: Dawn of the Dinosaurs', 'Action|Adventure|Animation|Children|Comedy|Romance', 'synthesize synergistic e-business', 16, 'Disponible', '2023-12-26 17:56:29', '2024-04-22 13:47:14');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (81, 68, 'Daydreams', 'Comedy', 'deploy e-business users', 40, 'Disponible', '2023-12-19 13:11:34', '2024-03-26 20:14:35');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (82, 5, 'Passion Flower', 'Drama', 'generate e-business ROI', 30, 'Disponible', '2023-12-08 18:28:36', '2024-03-08 03:37:06');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (83, 11, 'Good Thief, The', 'Crime|Drama', 'orchestrate interactive paradigms', 50, 'En curso', '2023-12-26 13:01:20', '2024-02-12 17:09:03');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (84, 62, 'At Play in the Fields of the Lord', 'Drama', 'target cutting-edge solutions', 37, 'En curso', '2023-12-09 03:35:31', '2024-02-01 15:23:01');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (85, 73, 'Fever Pitch', 'Comedy|Romance', 'implement holistic mindshare', 41, 'Finalizado', '2023-12-14 18:48:10', '2024-04-03 13:38:07');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (86, 67, 'Appleseed (Appurushîdo)', 'Action|Animation|Fantasy|Sci-Fi', 'harness vertical users', 50, 'En curso', '2023-12-30 07:41:54', '2024-04-12 02:35:28');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (87, 75, 'Parallels', 'Sci-Fi', 'innovate out-of-the-box paradigms', 36, 'Disponible', '2023-12-20 07:43:29', '2024-04-20 09:10:12');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (88, 27, 'House Bunny, The', 'Comedy', 'aggregate global e-business', 16, 'En curso', '2023-12-12 08:38:33', '2024-03-18 22:14:18');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (89, 7, 'My Life and Times With Antonin Artaud (En compagnie d''Antonin Artaud)', 'Drama', 'seize bricks-and-clicks initiatives', 12, 'Finalizado', '2023-12-01 09:23:31', '2024-01-03 19:20:31');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (90, 18, 'Buck', 'Documentary', 'iterate back-end e-commerce', 46, 'En curso', '2023-12-03 14:12:00', '2024-02-25 01:44:42');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (91, 95, 'Demon Seed', 'Horror|Sci-Fi|Thriller', 'generate sexy users', 48, 'En curso', '2023-12-27 16:19:23', '2024-04-28 21:21:47');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (92, 50, 'Nun, The (La religieuse)', 'Drama', 'productize mission-critical eyeballs', 35, 'Disponible', '2023-12-27 13:44:58', '2024-04-26 13:22:29');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (93, 62, 'Angela''s Ashes', 'Drama', 'morph turn-key eyeballs', 41, 'Finalizado', '2023-12-18 20:59:31', '2024-04-12 01:59:11');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (94, 35, 'Enemy', 'Mystery|Thriller', 'innovate distributed partnerships', 13, 'Disponible', '2023-12-05 03:51:19', '2024-02-20 18:27:25');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (95, 98, 'Home Run', 'Drama', 'strategize ubiquitous action-items', 11, 'En curso', '2023-12-11 15:01:47', '2024-03-05 23:43:14');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (96, 79, 'Summer of ''42', 'Drama', 'synthesize front-end e-commerce', 42, 'Disponible', '2023-12-28 14:03:29', '2024-03-28 11:25:15');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (97, 30, 'Berserk: The Golden Age Arc - The Egg of the King', 'Action|Adventure|Animation|Fantasy|Horror', 'productize back-end niches', 49, 'Finalizado', '2023-12-14 22:25:48', '2024-04-10 13:49:58');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (98, 16, 'Scenes from the Class Struggle in Beverly Hills', 'Comedy', 'embrace customized paradigms', 17, 'En curso', '2023-12-15 14:48:09', '2024-03-22 23:18:53');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (99, 11, 'Dark Skies', 'Horror|Sci-Fi|Thriller', 'innovate clicks-and-mortar systems', 11, 'Disponible', '2023-12-05 15:22:21', '2024-02-15 13:20:07');
INSERT INTO TORNEO (Id_Torneo, ID_Admin, Nombre, Juego, Reglas, Num_participantes, Estatus, Inicio, Fin) VALUES (100, 6, 'Arabesque', 'Adventure|Drama|Romance|Thriller', 'envisioneer mission-critical markets', 17, 'Disponible', '2023-12-15 23:04:29', '2024-01-10 07:45:03');

-- PARTICIPAR 

INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (13, 96, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (25, 61, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (99, 74, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (90, 4, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (22, 65, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (5, 25, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (89, 35, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (36, 11, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (90, 10, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (96, 32, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (91, 22, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (39, 74, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (95, 97, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (18, 82, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (44, 36, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (3, 96, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (52, 45, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (23, 26, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (59, 72, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (55, 94, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (17, 31, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (97, 96, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (10, 22, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (88, 35, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (40, 38, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (63, 36, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (3, 34, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (76, 87, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (78, 44, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (15, 18, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (93, 52, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (61, 25, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (90, 82, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (68, 22, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (26, 54, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (21, 68, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (65, 64, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (80, 66, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (99, 96, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (93, 72, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (94, 2, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (73, 72, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (31, 90, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (84, 20, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (14, 33, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (7, 94, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (78, 90, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (44, 21, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (57, 38, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (20, 61, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (86, 32, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (32, 84, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (77, 82, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (55, 12, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (97, 77, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (13, 82, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (69, 77, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (39, 20, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (66, 69, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (84, 1, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (25, 34, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (82, 12, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (37, 45, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (98, 46, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (84, 45, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (46, 85, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (29, 32, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (61, 77, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (42, 97, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (49, 95, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (99, 64, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (81, 59, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (92, 2, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (55, 72, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (64, 24, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (56, 64, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (32, 50, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (64, 56, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (98, 45, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (94, 48, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (46, 9, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (95, 45, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (7, 55, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (82, 23, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (37, 2, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (63, 45, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (99, 79, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (100, 6, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (21, 29, 'Ganador');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (54, 19, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (54, 26, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (58, 84, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (63, 77, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (28, 74, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (52, 72, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (42, 16, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (72, 97, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (94, 67, 'En curso');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (99, 23, 'Perdedor');
INSERT INTO PARTICIPAR (Id_Torneo, Id_Jugador, Resultado) VALUES (12, 78, 'En curso');


-- AMISTAD 

INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (55, 64);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (79, 28);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (74, 95);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (13, 25);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (60, 55);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (28, 32);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (46, 16);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (22, 40);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (1, 8);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (61, 10);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (49, 47);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (62, 77);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (13, 30);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (97, 66);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (63, 89);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (99, 41);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (68, 82);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (99, 49);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (29, 6);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (24, 95);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (35, 64);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (59, 71);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (3, 69);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (70, 35);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (17, 90);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (26, 3);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (27, 74);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (53, 44);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (32, 99);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (66, 22);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (70, 9);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (15, 92);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (39, 48);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (34, 25);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (54, 30);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (43, 46);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (70, 30);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (3, 86);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (5, 65);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (14, 55);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (61, 83);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (4, 59);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (57, 16);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (70, 67);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (25, 67);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (34, 55);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (1, 50);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (97, 11);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (59, 23);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (25, 48);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (99, 75);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (72, 75);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (24, 56);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (13, 48);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (50, 86);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (37, 35);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (34, 63);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (11, 36);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (97, 45);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (76, 95);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (56, 76);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (28, 19);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (67, 1);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (95, 21);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (61, 65);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (96, 45);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (99, 30);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (7, 20);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (45, 29);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (44, 48);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (83, 59);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (83, 8);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (92, 63);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (78, 51);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (51, 49);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (61, 14);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (56, 23);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (76, 97);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (50, 53);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (46, 9);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (43, 85);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (80, 92);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (89, 55);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (50, 70);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (87, 13);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (88, 83);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (23, 89);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (35, 70);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (78, 7);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (69, 21);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (14, 42);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (89, 83);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (61, 99);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (7, 89);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (1, 14);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (21, 20);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (40, 55);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (33, 45);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (95, 74);
INSERT INTO AMISTAD (Id_Jugador, Id_amigo) VALUES (21, 26);


